Repository psu-libraries/cho, pull requests merged in 2019-03, with the labels that each got.

#823 Changes to bag requirements
  app/cho/import/bag.rb
  app/cho/import/file.rb
  app/cho/import/file_set.rb
  app/cho/import/work.rb
  app/cho/metrics/repository.rb
  app/cho/work/file_set.rb
  spec/cho/import/bag_spec.rb
  spec/cho/import/file_set_spec.rb
  spec/cho/import/file_spec.rb
  spec/cho/import/work_spec.rb
  spec/cho/work/file_set_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/submissions/new_spec.rb
Labels: PR

#840 Change alternate identifiers to Valkyrie IDs
  .rubocop_todo.yml
  app/cho/validation/member.rb
  app/cho/work/import/work_hash_validator.rb
  spec/cho/validation/member_spec.rb
  spec/cho/work/import/create_spec.rb
Labels: PR

#841 Update Bootstrap to 4.3.1
  Gemfile
  Gemfile.lock
Labels: PR

#850 Delete extracted bags after validation and import
  app/cho/csv/controller_behavior.rb
  app/cho/csv/dry_run_behavior.rb
  app/cho/transaction/operations/import/csv.rb
  app/cho/transaction/operations/import/extract.rb
  spec/cho/agent/import/csv_dry_run_spec.rb
  spec/cho/transaction/operations/import/csv_spec.rb
Labels: PR

#851 Update to the latest new_relic_rpm gem
  Gemfile.lock
Labels: PR

#852 Adds the ability to update file sets through the UI
  .rubocop_todo.yml
  app/application/application_helper.rb
  app/cho/work/file_set.rb
  app/cho/work/file_set_change_set.rb
  app/cho/work/file_sets_controller.rb
  app/views/catalog/show.html.erb
  app/views/work/file_sets/_errors.html.erb
  app/views/work/file_sets/_form.html.erb
  app/views/work/file_sets/edit.html.erb
  config/locales/cho.yml
  config/routes.rb
  spec/cho/work/file_set/edit_spec.rb
  spec/cho/work/file_set/routing_spec.rb
  spec/cho/work/file_set_change_set_spec.rb
  spec/cho/work/file_set_spec.rb
  spec/cho/work/file_sets_controller_spec.rb
Labels: PR

#853 Validate creator input
  app/cho/validation/base.rb
  app/cho/validation/creator.rb
  app/cho/validation/factory.rb
  config/locales/cho.yml
  spec/cho/validation/creator_spec.rb
Labels: PR

#854 Ensure csv values are correctly escaped
  spec/cho/work/import/create_spec.rb
  spec/support/csv_factory/agent_update.rb
  spec/support/csv_factory/generic.rb
  spec/support/csv_factory/update.rb
  spec/support/metadata_factory.rb
Labels: PR

#855 ChangeSetPersister#delete should update parent resources
  app/blacklight/catalog_search_behavior.rb
  app/blacklight/document/csv.rb
  app/blacklight/solr_document.rb
  app/cho/collection/with_members.rb
  app/cho/import/work.rb
  app/cho/transaction/operations/file/save.rb
  app/cho/transaction/operations/import/work.rb
  app/cho/work/submission.rb
  app/cho/work/submission_change_set.rb
  app/valkyrie/change_set_persister.rb
  spec/blacklight/solr_document_spec.rb
  spec/cho/metrics/work_spec.rb
  spec/cho/transaction/operations/file/save_spec.rb
  spec/cho/transaction/operations/import/work_spec.rb
  spec/cho/work/file_set/delete_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/submissions/change_set_spec.rb
  spec/cho/work/submissions/submission_spec.rb
  spec/factories/file_sets.rb
  spec/valkyrie/change_set_persister_spec.rb
Labels: PR

#856 Parse agents and roles in csv files
  app/cho/agent/resource.rb
  app/cho/shared/csv_parsing.rb
  app/cho/work/import/work_hash_validator.rb
  spec/blacklight/solr_document_spec.rb
  spec/cho/csv/reader_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/csv_reader_spec.rb
  spec/factories/agent.rb
Labels: PR

#787 Updating to Blacklight 7.0.1
  Gemfile
  Gemfile.lock
  app/views/catalog/_document_members.html.erb
Labels: PR

#858 Fixing bugs with agent import
  app/cho/agent/csv_presenter.rb
  app/cho/agent/import/csv_dry_run.rb
  app/cho/agent/resources_controller.rb
  app/views/agent/import/csv/_dry_run_result.html.erb
  spec/cho/agent/controller_spec.rb
  spec/cho/agent/import/csv_dry_run_spec.rb
Labels: PR

#865 Assume a representative thumbnail if there isn't one
  app/cho/work/submission_indexer.rb
  spec/cho/work/submissions/new_spec.rb
Labels: PR

#869 allowing work type to have any case
  .rubocop_todo.yml
  app/cho/work/import/work_hash_validator.rb
  spec/cho/work/import/work_hash_validator_spec.rb
Labels: PR

#864 Rake task to batch load works from csv
  .rubocop_todo.yml
  app/cho/transaction/operations/import/csv.rb
  lib/tasks/ingest.rake
Labels: PR

#870 Adding a rake task to create a bag that is able to be imported
  .rubocop_todo.yml
  lib/tasks/bag.rake
Labels: PR

#871 Use correct use types in file fixtures
  spec/cho/repository/downloads_controller_spec.rb
  spec/factories/file_sets.rb
  spec/support/file_factory.rb
Labels: PR

#873 Updating Rails to 5.1.6
  Gemfile
  Gemfile.lock
Labels: PR

#880 Adding work type to csv export
  app/blacklight/document/csv.rb
  spec/blacklight/solr_document_spec.rb
Labels: PR

#882 disallow a changing work type in the validation
  app/cho/work/import/work_hash_validator.rb
  app/cho/work/submission_change_set.rb
  spec/cho/work/import/work_hash_validator_spec.rb
Labels: PR

#883 Adding a header line to work csv output
  app/blacklight/document/csv.rb
  spec/blacklight/solr_document_spec.rb
Labels: PR

#881 Adding a title so the display does not blow up
  app/cho/csv/hash_validator.rb
  config/locales/cho.yml
  spec/cho/csv/hash_validator_spec.rb
Labels: PR

#884 CSV metadata for works and file sets
  app/cho/work/import/csv_dry_run.rb
  app/cho/work/import/csv_dry_run_results_presenter.rb
  app/cho/work/import/file_set_hash_validator.rb
  app/cho/work/import/with_hash_creators.rb
  app/cho/work/import/work_hash_validator.rb
  app/views/work/import/csv/_dry_run_result.html.erb
  app/views/work/import/csv/dry_run_results.html.erb
  config/locales/cho.yml
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/support/import_factory/zip.rb
Labels: PR

#878 Data dictionary updates to date_created and rights_statement
  config/data_dictionary/data_dictionary_development.csv
  config/data_dictionary/data_dictionary_production.csv
Labels: PR, cataloger, discovery

#887 Sync data dictionary configs
  config/data_dictionary/data_dictionary_development.csv
  config/data_dictionary/data_dictionary_production.csv
Labels: PR

#879 Update UI labels
  config/locales/cho.yml
  spec/blacklight/catalog_spec.rb
  spec/cho/agent/import/update_spec.rb
  spec/cho/batch/delete_controller_spec.rb
  spec/cho/batch/delete_presenter_spec.rb
  spec/cho/batch/select_spec.rb
  spec/cho/collection/archival_collections/edit_spec.rb
  spec/cho/collection/archival_collections/new_spec.rb
  spec/cho/collection/curated_collections/edit_spec.rb
  spec/cho/collection/curated_collections/new_spec.rb
  spec/cho/collection/library_collections/edit_spec.rb
  spec/cho/collection/library_collections/new_spec.rb
  spec/cho/home_page_spec.rb
  spec/cho/metrics/collection_spec.rb
  spec/cho/work/file_set/delete_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/cho/work/submissions/change_set_spec.rb
  spec/cho/work/submissions/delete_spec.rb
  spec/cho/work/submissions/edit_spec.rb
  spec/cho/work/submissions/index_spec.rb
  spec/cho/work/submissions/new_spec.rb
  spec/cho/work/submissions/show_spec.rb
  spec/support/shared/collections.rb
  spec/support/shared/features.rb
  spec/views/archival_collections/edit.html.erb_spec.rb
  spec/views/archival_collections/new.html.erb_spec.rb
  spec/views/curated_collections/edit.html.erb_spec.rb
  spec/views/curated_collections/new.html.erb_spec.rb
  spec/views/library_collections/edit.html.erb_spec.rb
  spec/views/library_collections/new.html.erb_spec.rb
Labels: PR, UI

#904 Update Devise to 4.6.1
  Gemfile.lock
  config/initializers/devise.rb
  config/locales/devise.en.yml
Labels: PR

#903 Allow creators with no roles to index correctly
  app/cho/indexing/creator.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/update_spec.rb
Labels: PR

#905 Opened application to Penn State users
  Gemfile
  Gemfile.lock
  app/application/application_controller.rb
  app/devise/ability.rb
  app/views/_user_util_links.html.erb
  app/views/agent/resources/index.html.erb
  app/views/agent/resources/show.html.erb
  app/views/catalog/show.html.erb
  spec/application/request_spec.rb
  spec/cho/agent/index_spec.rb
  spec/cho/agent/show_spec.rb
  spec/cho/collection/archival_collections/show_spec.rb
  spec/cho/collection/curated_collections/show_spec.rb
  spec/cho/collection/library_collections/show_spec.rb
  spec/cho/home_page_spec.rb
  spec/cho/repository/downloads_controller_spec.rb
  spec/devise/ability_spec.rb
  spec/factories/users.rb
  spec/support/remote_authentication.rb
  spec/support/shared/collections.rb
Labels: PR

#906 Updating to fix searching
  app/blacklight/catalog_controller.rb
  app/cho/data_dictionary/field.rb
  solr/config/schema.xml
  spec/blacklight/catalog_spec.rb
  spec/cho/data_dictionary/field_spec.rb
Labels: PR

#910 Cleaning up ChangeSetPersister
  app/valkyrie/change_set_persister.rb
  spec/valkyrie/change_set_persister_spec.rb
Labels: PR

#911 Adding a new reindex task
  lib/tasks/index.rake
Labels: PR

#912 Open application to the public
  app/application/application_controller.rb
  app/devise/ability.rb
  app/devise/unauthorized_controller.rb
  config/initializers/devise_remote.rb
  spec/application/request_spec.rb
  spec/cho/agent/index_spec.rb
  spec/cho/agent/show_spec.rb
  spec/cho/home_page_spec.rb
  spec/cho/repository/downloads_controller_spec.rb
  spec/devise/ability_spec.rb
  spec/support/remote_authentication.rb
  spec/support/shared/collections.rb
Labels: PR

#907 Adds unique validation to alternative identifiers
  .rubocop_todo.yml
  app/cho/data_dictionary/fields_for_change_set.rb
  app/cho/validation/base.rb
  app/cho/validation/factory.rb
  app/cho/validation/member.rb
  app/cho/validation/unique.rb
  config/data_dictionary/data_dictionary_development.csv
  config/data_dictionary/data_dictionary_production.csv
  config/data_dictionary/data_dictionary_test.csv
  spec/cho/collection/archival_collections/new_spec.rb
  spec/cho/collection/curated_collections/new_spec.rb
  spec/cho/collection/library_collections/new_spec.rb
  spec/cho/validation/factory_spec.rb
  spec/cho/validation/member_spec.rb
  spec/cho/validation/unique_spec.rb
  spec/cho/work/submissions/edit_spec.rb
  spec/cho/work/submissions/new_spec.rb
  spec/factories/works.rb
Labels: PR

#915 Remove file upload from work edit form
  app/views/work/submissions/_form.html.erb
  spec/cho/work/submissions/edit_spec.rb
  spec/views/work_submissions/edit.html.erb_spec.rb
Labels: PR

#916 Default SolrDocument#file_sets to preservation file sets
  app/blacklight/solr_document.rb
  app/cho/work/submission.rb
  app/cho/work/submission_indexer.rb
  spec/blacklight/solr_document_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/cho/work/submissions/new_spec.rb
  spec/cho/work/submissions/submission_spec.rb
  spec/factories/file_sets.rb
Labels: PR

#914 Configuring member_of_collection_ids in the data dictionary
  app/blacklight/catalog_controller.rb
  app/blacklight/local_helper_behavior.rb
  app/cho/display_transformation/factory.rb
  config/data_dictionary/data_dictionary_development.csv
  config/data_dictionary/data_dictionary_production.csv
  config/data_dictionary/data_dictionary_test.csv
  spec/blacklight/catalog_spec.rb
  spec/cho/data_dictionary/csv_importer_spec.rb
  spec/cho/display_transformation/factory_spec.rb
  spec/cho/schema/work_type_configuration_spec.rb
  spec/cho/work/submissions/index_spec.rb
  spec/cho/work/submissions/new_spec.rb
  spec/cho/work/submissions/show_spec.rb
Labels: PR

#920 Changing member_of_collection to home_collection
  app/blacklight/collection_member_search_builder.rb
  app/blacklight/solr_document.rb
  app/cho/collection/with_members.rb
  app/cho/metrics/collection.rb
  app/cho/work/import/csv_dry_run.rb
  app/cho/work/import/csv_reader.rb
  app/cho/work/import/work_hash_validator.rb
  app/cho/work/submission_indexer.rb
  config/data_dictionary/data_dictionary_development.csv
  config/data_dictionary/data_dictionary_production.csv
  config/data_dictionary/data_dictionary_test.csv
  config/data_dictionary/schema_fields.yml
  lib/tasks/ingest.rake
  spec/blacklight/catalog_spec.rb
  spec/blacklight/solr_document_spec.rb
  spec/cho/batch/delete_presenter_spec.rb
  spec/cho/collection/with_members_spec.rb
  spec/cho/csv/importer_spec.rb
  spec/cho/schema/configuration_spec.rb
  spec/cho/schema/work_type_configuration_spec.rb
  spec/cho/transaction/operations/file/characterize_spec.rb
  spec/cho/transaction/operations/file/save_spec.rb
  spec/cho/transaction/operations/shared/save_spec.rb
  spec/cho/transaction/operations/shared/validate_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/csv_controller_spec.rb
  spec/cho/work/import/csv_dry_run_results_presenter_spec.rb
  spec/cho/work/import/csv_dry_run_spec.rb
  spec/cho/work/import/csv_reader_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/cho/work/import/work_hash_validator_spec.rb
  spec/cho/work/submissions/change_set_spec.rb
  spec/cho/work/submissions/index_spec.rb
  spec/cho/work/submissions/indexer_spec.rb
  spec/cho/work/submissions/new_spec.rb
  spec/cho/work/submissions/show_spec.rb
  spec/cho/work/submissions/submission_spec.rb
  spec/cho/work/submissions/submissions_controller_spec.rb
  spec/factories/works.rb
  spec/fixtures/cho_csv.csv
  spec/support/csv_factory/update.rb
  spec/support/shared/collections.rb
  spec/valkyrie/change_set_persister_spec.rb
  spec/views/work_submissions/new.html.erb_spec.rb
Labels: PR

#919 Buttons download representative work & plain text
  app/blacklight/solr_document.rb
  app/cho/work/submission.rb
  app/cho/work/submission_indexer.rb
  app/views/catalog/_download_representatives.html.erb
  app/views/catalog/_show_header.html.erb
  config/locales/cho.yml
  spec/blacklight/solr_document_spec.rb
  spec/cho/work/submissions/show_spec.rb
  spec/factories/works.rb
Labels: PR

#921 Show a fileset's files as a table with type, size
  app/cho/work/file.rb
  app/views/catalog/_show_work_fileset.html.erb
  config/initializers/mime_types.rb
  spec/cho/work/file_set/delete_spec.rb
  spec/cho/work/file_spec.rb
Labels: PR

#922 Adding a presenter method for the error messages
  app/cho/collection/change_set_behaviors.rb
  app/cho/work/file_set_change_set.rb
  app/cho/work/submission_change_set.rb
  app/cho/work/with_error_messages.rb
  app/views/work/import/csv/_dry_run_result.html.erb
  app/views/work/submissions/_errors.html.erb
  spec/cho/collection/archival_collections/edit_spec.rb
  spec/cho/collection/archival_collections/new_spec.rb
  spec/cho/collection/curated_collections/edit_spec.rb
  spec/cho/collection/curated_collections/new_spec.rb
  spec/cho/collection/library_collections/edit_spec.rb
  spec/cho/collection/library_collections/new_spec.rb
  spec/cho/work/import/create_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/cho/work/submissions/edit_spec.rb
  spec/cho/work/submissions/new_spec.rb
Labels: PR
