Repository psu-libraries/cho, pull requests merged in 2019-05, with the labels that each got.

#971 Update changelog for MVP 6 release
  changelog.md
Labels: MVP, PR

#972 Updating to Ruby 2.6.3
  .rubocop.yml
  .ruby-version
  .travis.yml
  Gemfile.lock
  app/blacklight/metadata_field_presenter.rb
  app/blacklight/solr_document.rb
  app/cho/agent/change_set.rb
  app/cho/agent/import/csv_dry_run.rb
  app/cho/batch/delete_presenter.rb
  app/cho/csv/dry_run_transaction.rb
  app/cho/import/work.rb
  app/cho/indexing/creator.rb
  app/cho/repository/config_file.rb
  app/cho/repository/configuration.rb
  app/cho/repository/download.rb
  app/cho/repository/file_use.rb
  app/cho/schema/input_field.rb
  app/cho/schema/metadata_field.rb
  app/cho/transaction/operations/file/characterize.rb
  app/cho/transaction/operations/file/create.rb
  app/cho/transaction/operations/file/create_temp_file.rb
  app/cho/transaction/operations/file/save.rb
  app/cho/transaction/operations/file_set/extract_text.rb
  app/cho/transaction/operations/import/csv.rb
  app/cho/transaction/operations/import/extract.rb
  app/cho/transaction/operations/import/validate.rb
  app/cho/transaction/operations/import/work.rb
  app/cho/transaction/operations/import/zip.rb
  app/cho/transaction/operations/shared/save.rb
  app/cho/validation/creator.rb
  app/cho/validation/unique.rb
  app/cho/work/import/csv_dry_run.rb
  app/cho/work/import/with_hash_creators.rb
  app/cho/work/submission.rb
  app/cho/work/submission_change_set.rb
  app/cho/work/submission_indexer.rb
  app/valkyrie/change_set_persister.rb
  app/views/_manage.html.erb
  app/views/shared/input_partials/_creator.html.erb
  config/initializers/shrine.rb
  lib/tasks/bag.rake
  lib/tasks/ingest.rake
  spec/blacklight/catalog_spec.rb
  spec/cho/csv/hash_validator_spec.rb
  spec/cho/indexing/linked_fields_spec.rb
  spec/cho/schema/input_field_spec.rb
  spec/cho/schema/metadata_field_change_set_spec.rb
  spec/cho/validation/factory_spec.rb
  spec/cho/work/file_set_change_set_spec.rb
  spec/cho/work/import/csv_controller_spec.rb
  spec/cho/work/import/update_spec.rb
  spec/cho/work/import/work_hash_validator_spec.rb
  spec/cho/work/submissions/show_spec.rb
  spec/support/file_factory.rb
  spec/support/remote_authentication.rb
  spec/views/data_dictionary_fields/show.html.erb_spec.rb
  travis/test.sh
Labels: PR

#978 Retry click actions
  spec/cho/work/submissions/multiple_fields_spec.rb
  spec/support/webdriver_helpers.rb
Labels: PR

#982 Report Transaction errors in NewRelic, raise them in development
  .rubocop_todo.yml
  app/cho/shared/error_reporting_service.rb
  app/cho/transaction/operations/container.rb
  app/cho/transaction/operations/file/characterize.rb
  app/cho/transaction/operations/file/create.rb
  app/cho/transaction/operations/file/create_temp_file.rb
  app/cho/transaction/operations/file/process.rb
  app/cho/transaction/operations/file/save.rb
  app/cho/transaction/operations/file_set/extract_text.rb
  app/cho/transaction/operations/import/extract.rb
  app/cho/transaction/operations/import/validate.rb
  app/cho/transaction/operations/import/work.rb
  app/cho/transaction/operations/import/zip.rb
  app/cho/transaction/operations/shared/validate.rb
  app/cho/transaction/rejection.rb
  app/cho/transaction/shared/save_with_change_set.rb
  app/valkyrie/change_set_persister.rb
  spec/cho/csv/importer_spec.rb
  spec/cho/shared/error_reporting_service_spec.rb
  spec/cho/transaction/operations/file/process_spec.rb
  spec/cho/transaction/operations/import/zip_spec.rb
  spec/cho/transaction/operations/shared/validate_spec.rb
  spec/cho/transaction/rejection_spec.rb
Labels: blocked
